import type { NextPage } from "next";
import Head from "next/head";
import NavBarComponent from "../components/navbar/navbar-component";
import LandingPageComponent from "../components/landing-page/landing-page-component";
import FooterComponent from "../components/footer/footer-component";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Odd Job</title>
        <meta name="description" content="Generated by Odd Job" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBarComponent isMenu={false} />
      <LandingPageComponent />
      <FooterComponent />
    </div>
  );
};

export default Home;
