import type { NextPage } from "next";
import Head from "next/head";
import MenuPageComponent from "../components/menu-page/menu-page-component";
import NavBarComponent from "../components/navbar/navbar-component";

const Menu: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Odd Job</title>
        <meta name="description" content="Generated by Odd Job" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBarComponent isMenu={true} />
      <MenuPageComponent />
    </div>
  );
};

export default Menu;
